### ISSUE TITLE
How to clean all signature?

### ISSUE THREAD

**Issue by henry-zhuang** [kshenoy/vim-signature#90] opened 2015-07-06 03:59 UTC

**Comment by kshenoy** [comment] 2015-07-07 18:21
You can use `m<Space>` and `m<BS>` to remove the signs for all the marks and markers respectively.

From the doc:

    m<Space>     Delete all marks from the current buffer
    m<BS>        Remove all markers

**Comment by henry-zhuang** [comment] 2015-07-08 01:51
@kshenoy I try it, but it is invalid.

**Comment by kshenoy** [comment] 2015-07-08 17:51
Ok, then I think I misunderstood your question. Could you please elaborate on what you're trying to do?

**Comment by henry-zhuang** [comment] 2015-07-09 02:05
@kshenoy 

Sorry, I try my best to elaborate in English.

I open a file such hello.go
I type `mm` for mark this line.
Now, I want to delete this mark, how should I do?

**Comment by kshenoy** [comment] 2015-07-09 04:16
Ah, ok. There are multiple ways to remove the mark. They are

1. If you're on the line, press `mm` again to remove mark 'm'.
2. If you're on any other line, you can press `dmm` to remove mark 'm'
3. `m-` will remove all marks from the current line
4. `m<Space>` will remove all marks from the current buffer

Hope that helps

**Comment by henry-zhuang** [comment] 2015-07-09 05:12
@kshenoy It‘s strange. I use four ways, but couldn't delete mark.

**Comment by kshenoy** [comment] 2015-07-09 05:27
Umm, that is really weird. What does the file hello.go contain? Is it empty?

**Comment by henry-zhuang** [comment] 2015-07-09 07:34
@kshenoy 

```
package main

import (
	"fmt"
	"strconv"
	"time"
)

func main() {
	fmt.Printf("%x", strconv.FormatInt((time.Now().Unix()), 10))
}
```
Not only hello.go, other file can't delete mark.

**Comment by kshenoy** [comment] 2015-07-09 14:28
Ok, I tried it at my end and it works fine; I don't why it doesn't work for you.

Can you please do the following:

1. Open a file without any marks present it
2. Place a mark 'm' using `mm` anywhere in the file
3. Paste here the output of `:marks m`
4. Paste here the output of `echo b:sig_marks`
5. Paste here the output of `:map m`

Thanks

**Comment by henry-zhuang** [comment] 2015-07-09 14:52
@kshenoy 

This is my output

```
marks m
mark line  col file/text
 m     35    0 **In OSX with Homebrew**
```

echo b:sig_marks
```
{'35': 'm'}
```

:map m
```
No mapping found
```

**Comment by kshenoy** [comment] 2015-07-09 15:16
Ah! That's interesting. The mapping doesn't exist. That is why you are not able to delete marks. 
Probably some setting in your config is deleting the maps.

Can you try starting vim with the following command (change the path to wherever you have installed vim-signature):

    vim -Nu <(echo 'set rtp+=~/.vim/bundle/vim-signature/')

and see if you're able to delete marks?

**Comment by henry-zhuang** [comment] 2015-07-09 15:28
@kshenoy Ok, it works.

How can I modify my .vimrc?

This is my .vimrc
https://github.com/henry-zhuang/dotfile/blob/master/.vimrc

**Comment by kshenoy** [comment] 2015-07-09 15:53
Ah, that's the painful part. Here are the steps I'd follow:

First, comment all `Plugin` calls except `Plugin 'kshenoy/vim-signature'` in plugin.vim. This will tell us if some other plugin is deleting the maps or if it is some setting in your main .vimrc

Next, use binary search ie. comment out half the plugins, see if Signature works or not. If it does not work, then the problem is inside the still active half. Otherwise the problem is in the disabled half. Repeat with binary divisions as necessary.

**Comment by henry-zhuang** [comment] 2015-07-09 16:56
@kshenoy Binary search is a good way.

I want to streamline my plugin file, how can I do better?

**Comment by kshenoy** [comment] 2015-07-09 17:22
Hmm, take a look at [my vimrc](https://github.com/kshenoy/dotvim/blob/master/vimrc). I use the variable DISABLE_FROM to help me with binary searches.

Also check out [Bisectly](https://github.com/dahu/bisectly)

**Comment by kshenoy** [comment] 2015-07-18 09:14
Closing this as I assume the original issue has been resolved. Please reopen in case of any questions

**Closed by kshenoy** 2015-07-18 09:14 UTC
