### ISSUE TITLE
Removing marks seems broken

### ISSUE THREAD

**Issue by alexlafroscia** [kshenoy/vim-signature#101] opened 2015-11-14 21:45 UTC
I can place a mark using, for example, `me` (which is just part of the default Vim behavior).  However, deleting a mark through `dme` does not work, it just moves to the end of the next word (like `e` normally would).

**Comment by kshenoy** [comment] 2015-11-15 17:18
That's weird. It works at my end.  What is the output of `:map dm`?

Also, I moved some files around recently. Can you try completely uninstalling and reinstalling it and see if that helps.

**Comment by alexlafroscia** [comment] 2015-11-15 17:32
The output of `:map dm` is:

```
n dm * :<C-U>call signature#utils#Remove(v:count)<CR>
```

**Comment by kshenoy** [comment] 2015-11-18 03:38
Ok, I'm unable to reproduce this.

Can you try starting vim with only Signature and see if the issue still exists? Try this `gvim -Nu <(echo 'set rtp+=~/.vim/bundle/vim-signature/')`

If yes, then tell me the output of `echo b:sig_marks` after you try place the mark `me` and also after you execute `dme`

**Comment by alexlafroscia** [comment] 2015-11-25 17:43
After `me`:

```
{'5': 'e'}
```

After `dme`:

```
{}
```

It doesn't seem to have a problem when using _just_ `vim-signature`.  I wonder which other plugin is conflicting... I can start searching but it'll take a while.

**Comment by ilaipi** [comment] 2015-12-21 07:59
@alexlafroscia Hello, is it solved? I use wklken/k-vim and this trouble me too.

**Comment by alexlafroscia** [comment] 2015-12-21 20:02
No, I haven't dug into which other vim plugin is messing with things.

**Comment by lord** [comment] 2015-12-26 06:35
Have this problem, too! Using neovim. Seems to occur when I don't have other plugins installed, but I just switched back to vim after ~3 years of sublime, so maybe I'm just doing something wrong. Also using vim-plug.

**Comment by kshenoy** [comment] 2015-12-28 03:28
@lord Do you get it even when Signature is the only thing installed? Test it with `gvim -N u <(echo 'set rtp+=~/.vim/bundle/vim-signature') -U NONE`

Replace `~/.vim/bundle/vim-signature` with wherever you're installing plugins if you're not using the standard settings.

**Comment by nedbat** [comment] 2015-12-28 21:28
Removing marks works for me (using `mm` to set and also `mm` to remove), until somehow it stops working.  I wish I had more information for you.

**Comment by lord** [comment] 2016-01-01 22:03
@kshenoy Hmm, like I said, using neovim, which doesn't appear to have `-N or `-U` flags, at least in the man page? I tried uninstalling all other plugins, and it was still happening.

**Comment by kshenoy** [comment] 2016-01-07 01:33
@lord Ah, ok. I'm not familiar with Neovim myself. If you guys could let me know how to reproduce this then I'd appreciate it but till then I can't help but sit here twiddling my thumbs

**Comment by nedbat** [comment] 2016-01-07 14:10
@kshenoy it happened to me again, so I grabbed the output of ":map", then restarted vim, and got the output of ":map" again.  The difference is that all of the vim-signature bindings are gone:
```
14,15d13
< n  '[          * :<C-U>call signature#mark#Goto("prev", "line", "alpha")<CR>
< n  ']          * :<C-U>call signature#mark#Goto("next", "line", "alpha")<CR>
54,57d51
< n  [=          * :<C-U>call signature#marker#Goto("prev", "any",  v:count)<CR>
< n  [-          * :<C-U>call signature#marker#Goto("prev", "same", v:count)<CR>
< n  [`          * :<C-U>call signature#mark#Goto("prev", "spot", "pos")<CR>
< n  ['          * :<C-U>call signature#mark#Goto("prev", "line", "pos")<CR>
140,143d133
< n  ]=          * :<C-U>call signature#marker#Goto("next", "any",  v:count)<CR>
< n  ]-          * :<C-U>call signature#marker#Goto("next", "same", v:count)<CR>
< n  ]`          * :<C-U>call signature#mark#Goto("next", "spot", "pos")<CR>
< n  ]'          * :<C-U>call signature#mark#Goto("next", "line", "pos")<CR>
187,188d176
< n  `[          * :<C-U>call signature#mark#Goto("prev", "spot", "alpha")<CR>
< n  `]          * :<C-U>call signature#mark#Goto("next", "spot", "alpha")<CR>
216d203
< n  dm          * :<C-U>call signature#utils#Remove(v:count)<CR>
242,249d228
< n  m?          * :<C-U>call signature#marker#List()<CR>
< n  m/          * :<C-U>call signature#mark#List("buf_curr")<CR>
< n  m<BS>       * :<C-U>call signature#marker#Purge()<CR>
< n  m<Space>    * :<C-U>call signature#mark#Purge("all")<CR>
< n  m-          * :<C-U>call signature#mark#Purge("line")<CR>
< n  m.          * :<C-U>call signature#mark#ToggleAtLine()<CR>
< n  m,          * :<C-U>call signature#mark#Toggle("next")<CR>
< n  m           * :<C-U>call signature#utils#Input()<CR>
```
I don't know what makes it happen though.

**Comment by kshenoy** [comment] 2016-01-08 02:14
@nedbat Ok, the fact that the whole thing goes kaput helps. It looks like to avoid conflicts with NerdTree, I delete all mappings when entering a NerdTree pane and recreate it when exiting it. Are you doing anything of that sort?

**Comment by nedbat** [comment] 2016-01-08 12:04
I do use NerdTree.  I can pay attention to what might be happening there.

**Comment by bcoady** [comment] 2016-02-09 15:56
I too was having conflicts with NerdTree. I commented out these two lines in Signature.vim and it all seems to work well now. 

`"    autocmd BufEnter,FileType * if (&filetype ==? 'nerdtree') | call signature#utils#Maps('remove') | endif
"    autocmd BufLeave * if (&filetype ==? 'nerdtree') | call signature#utils#Maps('create') | endif`

These lines were attempting to delete and recreate the mappings when entering and leaving NerdTree, except they didn't work when opening a new buffer from NerdTree.

**Comment by nedbat** [comment] 2016-02-10 10:03
@bcoady I'm trying to reproduce the problem using NerdTree, but I'm not seeing it.  The behavior with a new buffer in a new gvim is the same as after I open a new buffer from NerdTree.

**Comment by Hans-Guenter** [comment] 2016-02-19 10:56
There is an unbalance betweeen the autocommands for removing and creating the mappings.
The autocommand for removing acts on filetypes nerdtree and netrw while the latter only on the nerdtree one.
The corresponding autocommand should read:
    autocmd BufLeave * if **(** (&filetype ==? 'nerdtree')
                     **\ || (&filetype ==? 'netrw')**
                     **\ )**
                     \|  call signature#utils#Maps('create')
                     \| endif

**Comment by kshenoy** [comment] 2016-02-19 13:16
@Hans-Guenter You're right. Thanks for spotting that :)

**Comment by kshenoy** [comment] 2016-04-09 14:29
Closing this as I assume it's been dealt with. Feel free to reopen if required.

**Closed by kshenoy** 2016-04-09 14:29 UTC
Labels: bug

**Comment by Torwori** [comment] 2016-05-08 15:00
@kshenoy I'm having this issue while using `vim-nerdtree-tabs`, it goes away when I jump to the NerdTree buffer and then back to the file.

**Comment by kshenoy** [comment] 2016-05-11 02:11
Hey @Torwori I'm very busy with work now. I'll take a look at this during the weekend. 

If you have a way to reproduce this every time, can you please elaborate?

**Comment by Torwori** [comment] 2016-05-11 16:49
I've since removed nerdtree-tabs, but basically none of the expected
bindings (eg. dma) would work in a newly opened tab unless I entered and
exited the nerdtree buffer first.

**Comment by chenhouwu** [comment] 2016-05-30 06:43
see: #3

**Comment by kshenoy** [comment] 2016-05-30 23:30
Please refer to [my response](https://github.com/kshenoy/vim-signature/issues/3#issuecomment-222565292) for a workaround. I'm kind of tired dancing around this issue and will probably just go down this path permanently since I can't think of a better way to deal with it.
