### ISSUE TITLE
Toggling folds is slow

### ISSUE THREAD

**Issue by andreasthoelke** [kshenoy/vim-signature#85] opened 2015-04-23 10:44 UTC
Expanding and collapsing folds takes about 900 milliseconds, when I have vim-signature enabled in my vimrc via `Plugin 'kshenoy/vim-signature'`. If vim-signature is disabled, expanding and collapsing folds works instant.

I'm using gVim 7.4 on Win 8.1.

**Comment by kshenoy** [comment] 2015-04-23 16:42
Would it be possible to send this file? If not, can you give me some infomation on how many lines are in that file, how many folds, how many marks etc.

**Comment by andreasthoelke** [comment] 2015-04-24 11:57
Thank you for looking into this!

I can reproduce the behavior like this:

With `Plugin 'kshenoy/vim-signature'` commented out:
* Create a new text file with 4 lines of text (one word each)
* fold lines 2-3

Toggling of the fold is now instant.

Then 
* uncomment `Plugin 'kshenoy/vim-signature'`
* restart vim

Now toggling of the same fold is slow (takes approx. 900ms).

* comment out `Plugin 'kshenoy/vim-signature'`
* restart vim

The same fold toggles instantly. 

No marks were set during the test.

**Comment by andreasthoelke** [comment] 2015-04-24 12:06
I suspect that maybe I'm using another plugin that is interfering with vim-signature. Here is the list of plugins I use:

```
Plugin 'gmarik/Vundle.vim'

" File manager
Plugin 'scrooloose/nerdtree'
Plugin 'kien/ctrlp.vim'
" Plugin 'jeetsukumaran/vim-buffergator'

Plugin 'mileszs/ack.vim'
Plugin 'rking/ag.vim'

Plugin 'bling/vim-airline'
Plugin 'bling/vim-bufferline'

" Plugin 'gcavallanti/vim-noscrollbar' 
" Plugin 'kshenoy/vim-signature'

" Plugin 'terryma/vim-smooth-scroll'
Plugin 'yonchu/accelerated-smooth-scroll'

Plugin 'AndrewRadev/linediff.vim'

" Vim session & shell
Plugin 'xolox/vim-misc'
Plugin 'xolox/vim-session'
" Restore folding
Plugin 'vim-scripts/restore_view.vim'

Plugin 'xolox/vim-shell'
" iTerm2 integration
Plugin 'sjl/vitality.vim'

Plugin 'tomasr/molokai'

" REPL
Plugin 'tpope/vim-fireplace'
" Plugin 'tpope/vim-classpath'

" Leiningen
" Plugin 'tpope/vim-leiningen.git'
Plugin 'tpope/vim-projectionist.git'
Plugin 'tpope/vim-dispatch.git'

" General
Plugin 'guns/vim-clojure-static'
" Plugin 'majutsushi/tagbar'
Plugin 'pangloss/vim-javascript'

" S-Expression navigation
Plugin 'guns/vim-sexp'
Plugin 'tpope/vim-sexp-mappings-for-regular-people'

" Code utils
Plugin 'tpope/vim-surround'
Plugin 'tpope/vim-repeat'
" Plugin 'tpope/vim-commentary'
Plugin 'tomtom/tcomment_vim'

Plugin 'matze/vim-move'
Plugin 'terryma/vim-expand-region'
" Plugin 'terryma/vim-multiple-cursors'

" Plugin 'kien/rainbow_parentheses.vim'
Plugin 'amdt/vim-niji'
Plugin 'guns/vim-clojure-highlight'

Plugin 'chrisbra/Colorizer' 
Plugin 'KabbAmine/vCoolor.vim' 

" Highlight
" Plugin 't9md/vim-quickhl'
Plugin 'kana/vim-operator-user'
```

**Comment by kshenoy** [comment] 2015-04-24 16:31
If it's that easy to reproduce then I agree with you that it's probably due to interaction with some other plugin. Ok, let's try to narrow things down.

First, can you start vim with just vim-signature enabled using this command

    vim -Nu <(echo 'set rtp+=~/.vim/bundle/vim-signature/')

If folding is responsive, start vim using your setup but comment out all plugins except for Signature

Also, can you tell me what is the value of the updatetime variable (`verb set updatetime?`)

**Comment by andreasthoelke** [comment] 2015-04-25 18:18
A curious turn: I don't see the slow toggling of folds any more! I saw it consistently for two days, even after restarts. I can't remember what I have changed since then - I'm working on the same project with a mostly unchanged vimrc.
I will run the test you described if I come across the lag again.
Anyway, I'm happy that everything is fast now! Thanks again for looking into this!

**Comment by kshenoy** [comment] 2015-04-25 19:45
Umm, we didn't root-cause the issue. But... you're welcome? 

Closing this. Feel free to reopen if it pops up again

**Closed by kshenoy** 2015-04-25 19:45 UTC
