### ISSUE TITLE
m-space doesn't remove the sign gutter

### ISSUE THREAD

**Issue by nedbat** [kshenoy/vim-signature#106] opened 2016-02-07 15:24 UTC
If I set a mark with `mm`, the gutter appears with an `m` in it.  If I then remove the mark with `mm`, the gutter disappears, because the file has no marks.

If I set a mark with `mm`, and then remove it with `m<Space>` (remove all the marks), the gutter remains.  Shouldn't it disappear?

**Comment by kshenoy** [comment] 2016-02-07 17:37
It should. Can you tell what version of the plugin are you using?

**Comment by nedbat** [comment] 2016-02-08 00:25
Hmm, I have the latest version, and i just tried it again, and the gutter did go away.  Another flavor of mysterious disabling?

**Comment by kshenoy** [comment] 2016-02-08 12:02
Tbh, I have no idea. Suddenly there seems to be a stream of difficult to reproduce bugs : /

Closing this; feel free to reopen it if it pops up again

**Comment by iamcco** [comment] 2016-02-28 10:30
I have the same problem in neovim, see [here ](https://github.com/neovim/neovim/issues/4288)
@kshenoy may be you can update README for those using neovim

> This is by design (explained below). Note however that you can achieve your goal by force-writing the shada file without reading the existing one (note the "!" bang):

> :wshada!
> Vim's 'viminfo' behaves the same. It wouldn't make sense for Vim nor Nvim to delete marks after :delmarks upon exit, because there's no way to know if the marks in the existing file came from another Vim or Nvim instance. We don't annotate viminfo/shada records with anything that would identify the instance that the record came from.

**Comment by kshenoy** [comment] 2016-03-01 05:14
@iamcco Thanks for pointing it out.

Unfortunately, I don't use NeoVim. Can you please create a pull request and update it? Thanks

**Comment by kshenoy** [comment] 2017-08-16 05:10
Closing due to inactivity. Please feel free to reopen if the issue is still prevalent.

**Closed by kshenoy** 2017-08-16 05:10 UTC
